spring:
  application:
    name: bens-cloud-admin-eureka-server
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS