
server:
  port: 8095

spring:
  application:
    name: spring-cloud-config-client

info:
  head: head
  body: body
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    refresh:
      enabled: true
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false

