spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8100
server:
  port: 8110

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS